# Spring Boot 配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://Docker-Database:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      cache-enabled: true
      cache-unknown: true
      cache-lazy-loading-enabled: true
    mapperlocations: classpath:mapper/*.xml

# 配置日志级别 --- 数据库操作终端日志输出
logging:
  level:
    # 显示 Spring JDBC Template 执行的 SQL
    org.springframework.jdbc.core: DEBUG
    # 显示 Hibernate 执行的 SQL
    org.hibernate.SQL: DEBUG
    # 显示 Hibernate 绑定的参数值
    org.hibernate.type.descriptor.sql: TRACE
    # 显示 MyBatis Mapper 执行的 SQL
    com.example.myapp.Mapper: TRACE
